### ISSUE TITLE
User joins but doesn´t play any video or audio file

### ISSUE THREAD

**Issue by mkn-ta** [avstack/gst-meet#5]
Hi there,
we are an educational institution and we might like to use the project for a big project of us. However, we have the problem that the gst-meet user enters the room, but the user doesn´t play any audio or video file. We´ve tried a YouTube video and a .mp3 file, we did not get any error messages on the console and all required packages from GStreamer should be installed/compiled. We use Debian 10, Jitsi, GStreamer and gst-meet are all installed on one server. Do you have any idea what could cause the problem?
Thanks

**Comment by mkn-ta** [comment]
Thanks for you´re response, we´ve installed further plugins from package bad, now we´re getting this output when we try to play some .mp3 file with the command:

'cargo run --release -- --room-name test --verbose --nick "bot-user" --web-socket-url=wss://jitsi.example.com/xmpp-websocket --xmpp-domain=jitsi.example.com --send-pipeline="filesrc location=/root/test.mp3 ! queue ! mpegaudioparse ! mpg123audiodec ! audioconvert ! audioresample ! opusenc name=audio"

```Nov 01 11:50:32.976  INFO Connecting XMPP WebSocket to wss://jitsi.example.com/xmpp-websocket
Nov 01 11:50:32.990 DEBUG Client handshake done.
Nov 01 11:50:32.990 DEBUG XMPP    >>> <open xmlns="urn:ietf:params:xml:ns:xmpp-framing" to="jitsi.example.com" version="1.0"/>
Nov 01 11:50:32.991 DEBUG XMPP    <<< <open from='jitsi.example.com' version='1.0' id='891db802-f01f-4ef1-8d89-31b951b49be8' xml:lang='en' xmlns='urn:ietf:params:xml:ns:xmpp-framing'/>
Nov 01 11:50:32.991  INFO Connected XMPP WebSocket
Nov 01 11:50:32.991 DEBUG XMPP    <<< <stream:features xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams'><mechanisms xmlns='urn:ietf:params:xml:ns:xmpp-sasl'><mechanism>ANONYMOUS</mechanism></mechanisms></stream:features>
Nov 01 11:50:32.991 DEBUG XMPP    >>> <auth xmlns="urn:ietf:params:xml:ns:xmpp-sasl" mechanism="ANONYMOUS"></auth>
Nov 01 11:50:32.991 DEBUG XMPP    <<< <success xmlns='urn:ietf:params:xml:ns:xmpp-sasl'/>
Nov 01 11:50:32.991 DEBUG XMPP    >>> <open xmlns="urn:ietf:params:xml:ns:xmpp-framing" to="jitsi.example.com" version="1.0"/>
Nov 01 11:50:32.992 DEBUG XMPP    <<< <open from='jitsi.example.com' version='1.0' id='c6c1e655-0688-402e-9006-853e607f4df4' xml:lang='en' xmlns='urn:ietf:params:xml:ns:xmpp-framing'/>
Nov 01 11:50:32.992  INFO Logged in anonymously
Nov 01 11:50:32.992 DEBUG XMPP    <<< <stream:features xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams'><bind xmlns='urn:ietf:params:xml:ns:xmpp-bind'><required/></bind><session xmlns='urn:ietf:params:xml:ns:xmpp-session'><optional/></session><c ver='vxBnkHr84q8DpXesblwTtMRcbvo=' node='http://prosody.im' xmlns='http://jabber.org/protocol/caps' hash='sha-1'/><ver xmlns='urn:xmpp:features:rosterver'/></stream:features>
Nov 01 11:50:32.992 DEBUG XMPP    >>> <iq xmlns="jabber:client" id="45fa9eb9-13ea-4822-aecb-5e188851b74e" type="set"><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"/></iq>
Nov 01 11:50:32.992 DEBUG XMPP    <<< <iq xmlns='jabber:client' id='45fa9eb9-13ea-4822-aecb-5e188851b74e' type='result'><bind xmlns='urn:ietf:params:xml:ns:xmpp-bind'><jid>nre60ym5kkiokotr@jitsi.example.com/Rd7ZwkQ6</jid></bind></iq>
Nov 01 11:50:32.992  INFO My JID: nre60ym5kkiokotr@jitsi.example.com/Rd7ZwkQ6
Nov 01 11:50:32.992 DEBUG XMPP    >>> <iq xmlns="jabber:client" from="nre60ym5kkiokotr@jitsi.example.com/Rd7ZwkQ6" id="025c3681-7752-46e6-b568-13bd1c567ffc" to="jitsi.example.com" type="get"><query xmlns="http://jabber.org/protocol/disco#info"/></iq>
Nov 01 11:50:32.993 DEBUG XMPP    <<< <iq from='jitsi.example.com' id='025c3681-7752-46e6-b568-13bd1c567ffc' xmlns='jabber:client' type='result' to='nre60ym5kkiokotr@jitsi.example.com/Rd7ZwkQ6'><query xmlns='http://jabber.org/protocol/disco#info'><identity name='Prosody PubSub Service' category='pubsub' type='service'/><identity name='conferenceduration.jitsi.example.com' category='component' type='conference_duration'/><identity name='avmoderation.jitsi.example.com' category='component' type='av_moderation'/><identity name='Prosody' category='server' type='im'/><identity name='lobby.jitsi.example.com' category='component' type='lobbyrooms'/><identity name='Prosody' category='pubsub' type='pep'/><identity name='speakerstats.jitsi.example.com' category='component' type='speakerstats'/><feature var='http://jabber.org/protocol/pubsub'/><feature var='http://jabber.org/protocol/pubsub#publisher-affiliation'/><feature var='http://jabber.org/protocol/pubsub#create-nodes'/><feature var='http://jabber.org/protocol/pubsub#create-and-configure'/><feature var='http://jabber.org/protocol/pubsub#delete-nodes'/><feature var='http://jabber.org/protocol/pubsub#delete-items'/><feature var='http://jabber.org/protocol/pubsub#persistent-items'/><feature var='http://jabber.org/protocol/pubsub#retrieve-default'/><feature var='http://jabber.org/protocol/pubsub#access-open'/><feature var='http://jabber.org/protocol/pubsub#subscription-options'/><feature var='http://jabber.org/protocol/pubsub#config-node'/><feature var='http://jabber.org/protocol/pubsub#subscribe'/><feature var='http://jabber.org/protocol/pubsub#publish-options'/><feature var='http://jabber.org/protocol/pubsub#retrieve-items'/><feature var='http://jabber.org/protocol/pubsub#retract-items'/><feature var='http://jabber.org/protocol/pubsub#member-affiliation'/><feature var='http://jabber.org/protocol/pubsub#purge-nodes'/><feature var='http://jabber.org/protocol/pubsub#retrieve-subscriptions'/><feature var='http://jabber.org/protocol/pubsub#meta-data'/><feature var='http://jabber.org/protocol/pubsub#outcast-affiliation'/><feature var='http://jabber.org/protocol/pubsub#item-ids'/><feature var='http://jabber.org/protocol/pubsub#publish'/><feature var='http://jabber.org/protocol/pubsub#instant-nodes'/><feature var='http://jabber.org/protocol/pubsub#multi-items'/><feature var='http://jabber.org/protocol/pubsub#modify-affiliations'/><feature var='urn:xmpp:carbons:2'/><feature var='http://jabber.org/protocol/disco#info'/><feature var='http://jabber.org/protocol/disco#items'/><feature var='urn:xmpp:ping'/><feature var='http://jabber.org/protocol/commands'/><feature var='urn:xmpp:blocking'/><feature var='jabber:iq:roster'/><feature var='msgoffline'/><feature var='jabber:iq:private'/><feature var='jabber:iq:register'/><feature var='jabber:iq:version'/><feature var='urn:xmpp:time'/><feature var='jabber:iq:time'/><feature var='jabber:iq:last'/><feature var='urn:xmpp:extdisco:2'/><feature var='urn:xmpp:extdisco:1'/><feature var='vcard-temp'/></query></iq>
Nov 01 11:50:32.993 DEBUG XMPP    >>> <iq xmlns="jabber:client" from="nre60ym5kkiokotr@jitsi.example.com/Rd7ZwkQ6" id="5091e2ce-cb33-4eca-91fe-df51c8efff44" to="jitsi.example.com" type="get"><services xmlns="urn:xmpp:extdisco:2"/></iq>
Nov 01 11:50:32.993 DEBUG XMPP    <<< <iq from='jitsi.example.com' id='5091e2ce-cb33-4eca-91fe-df51c8efff44' xmlns='jabber:client' type='result' to='nre60ym5kkiokotr@jitsi.example.com/Rd7ZwkQ6'><services xmlns='urn:xmpp:extdisco:2'><service port='3478' type='stun' host='jitsi.example.com'/><service password='RVp/ltpp/cU/rum2QQ/wj/A9d3Q=' port='3478' transport='udp' expires='2021-11-02T10:50:32Z' username='1635850232' restricted='1' type='turn' host='jitsi.example.com'/><service password='RVp/ltpp/cU/rum2QQ/wj/A9d3Q=' port='5349' transport='tcp' expires='2021-11-02T10:50:32Z' username='1635850232' restricted='1' type='turns' host='jitsi.example.com'/></services></iq>
Nov 01 11:50:32.993 DEBUG external services: [Service { type: "stun", name: None, host: "jitsi.example.com", port: Some(3478), transport: None, restricted: None, username: None, password: None, expires: None }, Service { type: "turn", name: None, host: "jitsi.example.com", port: Some(3478), transport: Some("udp"), restricted: Some(true), username: Some("1635850232"), password: Some("RVp/ltpp/cU/rum2QQ/wj/A9d3Q="), expires: Some("2021-11-02T10:50:32Z") }, Service { type: "turns", name: None, host: "jitsi.example.com", port: Some(5349), transport: Some("tcp"), restricted: Some(true), username: Some("1635850232"), password: Some("RVp/ltpp/cU/rum2QQ/wj/A9d3Q="), expires: Some("2021-11-02T10:50:32Z") }]
Nov 01 11:50:32.993 DEBUG XMPP    >>> <iq xmlns="jabber:client" id="e093cb06-4cd6-4fd0-8421-ec51e01b5c62" to="focus@auth.jitsi.example.com/focus" type="set"><conference xmlns="http://jitsi.org/protocol/focus" machine-uid="b38c918b-0a9a-4bdf-bf90-f629ad27e407" room="test@conference.jitsi.example.com"><property name="startBitrate" value="800"/><property name="stereo" value="true"/></conference></iq>
Nov 01 11:50:32.995 DEBUG XMPP    <<< <iq from='focus@auth.jitsi.example.com/focus' id='e093cb06-4cd6-4fd0-8421-ec51e01b5c62' xmlns='jabber:client' type='result' to='nre60ym5kkiokotr@jitsi.example.com/Rd7ZwkQ6'><conference ready='true' xmlns='http://jitsi.org/protocol/focus' room='test@conference.jitsi.example.com' focusjid='focus@auth.jitsi.example.com'><property value='false' name='authentication'/></conference></iq>
Nov 01 11:50:32.995 DEBUG send_presence{self=JitsiConference { jid: FullJID(nre60ym5kkiokotr@jitsi.example.com/Rd7ZwkQ6), config: JitsiConferenceConfig { muc: BareJID(test@conference.jitsi.example.com), focus: Full(FullJID(focus@auth.jitsi.example.com/focus)), nick: "bot-user", region: None, video_codec: "vp8", extra_muc_features: [] }, inner: Mutex { data: JitsiConferenceInner { state: Discovering } } } payloads=[Element { name: "x", namespace: "http://jabber.org/protocol/muc", prefix: None, prefixes: Prefixes(), attributes: {}, children: [] }, Element { name: "c", namespace: "http://jabber.org/protocol/caps", prefix: None, prefixes: Prefixes(), attributes: {"hash": "sha-1", "node": "https://github.com/avstack/gst-meet", "ver": "swMAgANtyBNi66ghGYklxmQQoAQ="}, children: [] }, Element { name: "c", namespace: "urn:xmpp:caps", prefix: None, prefixes: Prefixes(), attributes: {}, children: [Element(Element { name: "hash", namespace: "urn:xmpp:hashes:2", prefix: None, prefixes: Prefixes(), attributes: {"algo": "sha-256"}, children: [Text("G/kN7Lvb58mV9M0f+E0V9ctHF3+2rT5irZCuqldbjGU=")] })] }, Element { name: "stats-id", namespace: "jabber:client", prefix: None, prefixes: Prefixes(), attributes: {}, children: [Text("gst-meet")] }, Element { name: "jitsi_participant_codecType", namespace: "jabber:client", prefix: None, prefixes: Prefixes(), attributes: {}, children: [Text("vp8")] }, Element { name: "audiomuted", namespace: "jabber:client", prefix: None, prefixes: Prefixes(), attributes: {}, children: [Text("false")] }, Element { name: "videomuted", namespace: "jabber:client", prefix: None, prefixes: Prefixes(), attributes: {}, children: [Text("false")] }, Element { name: "nick", namespace: "http://jabber.org/protocol/nick", prefix: None, prefixes: Prefixes(), attributes: {}, children: [Text("bot-user")] }]}: close time.busy=4.16µs time.idle=987ns
Nov 01 11:50:32.995 DEBUG XMPP    >>> <presence xmlns="jabber:client" to="test@conference.jitsi.example.com/nre60ym5kkiokotr"><x xmlns="http://jabber.org/protocol/muc"/><c xmlns="http://jabber.org/protocol/caps" hash="sha-1" node="https://github.com/avstack/gst-meet" ver="swMAgANtyBNi66ghGYklxmQQoAQ="/><c xmlns="urn:xmpp:caps"><hash xmlns="urn:xmpp:hashes:2" algo="sha-256">G/kN7Lvb58mV9M0f+E0V9ctHF3+2rT5irZCuqldbjGU=</hash></c><stats-id>gst-meet</stats-id><jitsi_participant_codecType>vp8</jitsi_participant_codecType><audiomuted>false</audiomuted><videomuted>false</videomuted><nick xmlns="http://jabber.org/protocol/nick">bot-user</nick></presence>
Nov 01 11:50:32.997 DEBUG XMPP    <<< <presence from='test@conference.jitsi.example.com/focus' xmlns='jabber:client' id='8EQBD-678' to='nre60ym5kkiokotr@jitsi.example.com/Rd7ZwkQ6'><priority>0</priority><etherpad xmlns='http://jitsi.org/jitmeet/etherpad'>test</etherpad><versions xmlns='http://jitsi.org/jitmeet'><component name='focus'>1.0.813</component></versions><conference-properties xmlns='http://jitsi.org/protocol/focus'><property value='true' key='support-terminate-restart'/><property value='0' key='bridge-count'/></conference-properties><c node='http://jitsi.org/jicofo' ver='Lg0vhCNhxjoeKJi2/hukdsizNWA=' xmlns='http://jabber.org/protocol/caps' hash='sha-1'/><x xmlns='vcard-temp:x:update'/><x xmlns='http://jabber.org/protocol/muc#user'><item jid='focus@auth.jitsi.example.com/focus' affiliation='owner' role='moderator'/></x></presence>
Nov 01 11:50:32.997 DEBUG XMPP    <<< <presence from='test@conference.jitsi.example.com/4d56b101' xmlns='jabber:client' to='nre60ym5kkiokotr@jitsi.example.com/Rd7ZwkQ6'><stats-id>Jordan-jPL</stats-id><c node='https://jitsi.org/jitsi-meet' ver='D50Kz2zZl6ZxcI7RzgE166vg6PM=' xmlns='http://jabber.org/protocol/caps' hash='sha-1'/><features><feature var='https://jitsi.org/meet/e2ee'/></features><jitsi_participant_codecType>vp8</jitsi_participant_codecType><nick xmlns='http://jabber.org/protocol/nick'>user</nick><jitsi_participant_e2ee.idKey>w0wKTTl6ZIROylGxgZnQfX15UtVfIj/PPrju3eY0fS4</jitsi_participant_e2ee.idKey><x xmlns='vcard-temp:x:update'/><x xmlns='http://jabber.org/protocol/muc#user'><item jid='1vmmmow2i0xxlsd6@jitsi.example.com/Es4hdO97' affiliation='owner' role='moderator'/></x></presence>
Nov 01 11:50:32.997 DEBUG XMPP    <<< <presence from='test@conference.jitsi.example.com/nre60ym5kkiokotr' xmlns='jabber:client' to='nre60ym5kkiokotr@jitsi.example.com/Rd7ZwkQ6'><c node='https://github.com/avstack/gst-meet' ver='swMAgANtyBNi66ghGYklxmQQoAQ=' xmlns='http://jabber.org/protocol/caps' hash='sha-1'/><c xmlns='urn:xmpp:caps'><hash algo='sha-256' xmlns='urn:xmpp:hashes:2'>G/kN7Lvb58mV9M0f+E0V9ctHF3+2rT5irZCuqldbjGU=</hash></c><stats-id>gst-meet</stats-id><jitsi_participant_codecType>vp8</jitsi_participant_codecType><audiomuted>false</audiomuted><videomuted>false</videomuted><nick xmlns='http://jabber.org/protocol/nick'>bot-user</nick><x xmlns='vcard-temp:x:update'/><x xmlns='http://jabber.org/protocol/muc#user'><status code='100'/><item jid='nre60ym5kkiokotr@jitsi.example.com/Rd7ZwkQ6' affiliation='none' role='participant'/><status code='110'/></x></presence>
Nov 01 11:50:32.997 DEBUG Joined MUC: test@conference.jitsi.example.com
Nov 01 11:50:32.997 DEBUG XMPP    <<< <message from='conferenceduration.jitsi.example.com' xmlns='jabber:client' to='nre60ym5kkiokotr@jitsi.example.com/Rd7ZwkQ6'><json-message xmlns='http://jitsi.org/jitmeet'>{&quot;type&quot;:&quot;conference_duration&quot;,&quot;created_timestamp&quot;:1635763547000}</json-message></message>
Nov 01 11:50:32.997 DEBUG XMPP    <<< <message from='speakerstats.jitsi.example.com' xmlns='jabber:client' to='nre60ym5kkiokotr@jitsi.example.com/Rd7ZwkQ6'><json-message xmlns='http://jitsi.org/jitmeet'>{&quot;type&quot;:&quot;speakerstats&quot;,&quot;users&quot;:{&quot;vdxktckgjcetvth_&quot;:{&quot;totalDominantSpeakerTime&quot;:0},&quot;9af07781&quot;:{&quot;displayName&quot;:&quot;user&quot;,&quot;totalDominantSpeakerTime&quot;:0},&quot;0mthbunmjg547pl3&quot;:{&quot;totalDominantSpeakerTime&quot;:0}}}</json-message></message>
Nov 01 11:50:32.997 DEBUG XMPP    <<< <message from='test@conference.jitsi.example.com' xmlns='jabber:client' type='groupchat' to='nre60ym5kkiokotr@jitsi.example.com/Rd7ZwkQ6'><subject/></message>
Nov 01 11:50:33.040 DEBUG XMPP    <<< <presence from='test@conference.jitsi.example.com/focus' xmlns='jabber:client' id='8EQBD-713' to='nre60ym5kkiokotr@jitsi.example.com/Rd7ZwkQ6'><priority>0</priority><etherpad xmlns='http://jitsi.org/jitmeet/etherpad'>test</etherpad><versions xmlns='http://jitsi.org/jitmeet'><component name='focus'>1.0.813</component></versions><conference-properties xmlns='http://jitsi.org/protocol/focus'><property value='true' key='support-terminate-restart'/><property value='1' key='bridge-count'/></conference-properties><c hash='sha-1' ver='Lg0vhCNhxjoeKJi2/hukdsizNWA=' xmlns='http://jabber.org/protocol/caps' node='http://jitsi.org/jicofo'/><x xmlns='vcard-temp:x:update'/><x xmlns='http://jabber.org/protocol/muc#user'><item jid='focus@auth.jitsi.example.com/focus' affiliation='owner' role='moderator'/></x></presence>
Nov 01 11:50:33.054 DEBUG XMPP    <<< <iq from='test@conference.jitsi.example.com/focus' id='bnJlNjB5bTVra2lva290ckBqaXRzaS0wMS50YS5kZS9SZDdad2tRNgA4RVFCRC03MjEA8dWe3ciFYT4irb3jIXm5CA==' xmlns='jabber:client' type='set' to='nre60ym5kkiokotr@jitsi.example.com/Rd7ZwkQ6'><jingle action='session-initiate' initiator='focus@auth.jitsi.example.com/focus' sid='7cbj7p7dg114t' xmlns='urn:xmpp:jingle:1'><content name='audio' creator='initiator' senders='both'><description media='audio' xmlns='urn:xmpp:jingle:apps:rtp:1' maxptime='60'><payload-type id='111' channels='2' name='opus' clockrate='48000'><parameter value='10' name='minptime'/><parameter value='1' name='stereo'/><parameter value='1' name='useinbandfec'/><rtcp-fb type='transport-cc' xmlns='urn:xmpp:jingle:apps:rtp:rtcp-fb:0'/></payload-type><payload-type name='ISAC' id='103' clockrate='16000'/><payload-type name='ISAC' id='104' clockrate='32000'/><payload-type name='telephone-event' id='126' clockrate='8000'/><rtp-hdrext xmlns='urn:xmpp:jingle:apps:rtp:rtp-hdrext:0' id='1' uri='urn:ietf:params:rtp-hdrext:ssrc-audio-level'/><rtp-hdrext xmlns='urn:xmpp:jingle:apps:rtp:rtp-hdrext:0' id='5' uri='http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01'/><rtcp-mux/><source name='jvb-a0' ssrc='190519583' xmlns='urn:xmpp:jingle:apps:rtp:ssma:0'><ssrc-info owner='jvb' xmlns='http://jitsi.org/jitmeet'/><parameter value='mixedmslabel mixedlabelaudio0' name='msid'/></source></description><transport xmlns='urn:xmpp:jingle:transports:ice-udp:1' pwd='5kgqi2tg75qcbrpdt1qcu3mq7v' ufrag='4v0g71fjdhui5d'><web-socket url='wss://jitsi.example.com:443/colibri-ws/default-id/3d98b6b81f3edade/nre60ym5kkiokotr?pwd=5kgqi2tg75qcbrpdt1qcu3mq7v' xmlns='http://jitsi.org/protocol/colibri'/><rtcp-mux/><fingerprint required='false' setup='actpass' xmlns='urn:xmpp:jingle:apps:dtls:0' hash='sha-256'>F9:DB:16:C4:DB:19:E4:F0:20:6C:EF:AD:0A:38:DC:B9:24:07:1B:D7:15:04:3E:1D:95:3C:14:7A:66:67:B9:45</fingerprint><candidate foundation='1' id='11ef07f522aca03406e3ba77b' component='1' protocol='udp' generation='0' network='0' ip='xxx:2' port='10000' type='host' priority='2130706431'/><candidate foundation='2' id='486e533922aca0340ffffffffa1b231b0' component='1' protocol='udp' generation='0' network='0' ip='xxx' port='10000' type='host' priority='2130706431'/></transport></content><content name='video' creator='initiator' senders='both'><description media='video' xmlns='urn:xmpp:jingle:apps:rtp:1'><payload-type name='VP8' id='100' clockrate='90000'><rtcp-fb subtype='fir' type='ccm' xmlns='urn:xmpp:jingle:apps:rtp:rtcp-fb:0'/><rtcp-fb type='nack' xmlns='urn:xmpp:jingle:apps:rtp:rtcp-fb:0'/><rtcp-fb subtype='pli' type='nack' xmlns='urn:xmpp:jingle:apps:rtp:rtcp-fb:0'/><parameter value='800' name='x-google-start-bitrate'/><rtcp-fb type='transport-cc' xmlns='urn:xmpp:jingle:apps:rtp:rtcp-fb:0'/></payload-type><payload-type name='H264' id='107' clockrate='90000'><rtcp-fb subtype='fir' type='ccm' xmlns='urn:xmpp:jingle:apps:rtp:rtcp-fb:0'/><rtcp-fb type='nack' xmlns='urn:xmpp:jingle:apps:rtp:rtcp-fb:0'/><rtcp-fb subtype='pli' type='nack' xmlns='urn:xmpp:jingle:apps:rtp:rtcp-fb:0'/><parameter value='800' name='x-google-start-bitrate'/><rtcp-fb type='transport-cc' xmlns='urn:xmpp:jingle:apps:rtp:rtcp-fb:0'/><parameter value='42e01f;level-asymmetry-allowed=1;packetization-mode=1;' name='profile-level-id'/></payload-type><payload-type name='VP9' id='101' clockrate='90000'><rtcp-fb subtype='fir' type='ccm' xmlns='urn:xmpp:jingle:apps:rtp:rtcp-fb:0'/><rtcp-fb type='nack' xmlns='urn:xmpp:jingle:apps:rtp:rtcp-fb:0'/><rtcp-fb subtype='pli' type='nack' xmlns='urn:xmpp:jingle:apps:rtp:rtcp-fb:0'/><parameter value='800' name='x-google-start-bitrate'/><rtcp-fb type='transport-cc' xmlns='urn:xmpp:jingle:apps:rtp:rtcp-fb:0'/></payload-type><payload-type name='rtx' id='96' clockrate='90000'><parameter value='100' name='apt'/><rtcp-fb subtype='fir' type='ccm' xmlns='urn:xmpp:jingle:apps:rtp:rtcp-fb:0'/><rtcp-fb type='nack' xmlns='urn:xmpp:jingle:apps:rtp:rtcp-fb:0'/><rtcp-fb subtype='pli' type='nack' xmlns='urn:xmpp:jingle:apps:rtp:rtcp-fb:0'/></payload-type><payload-type name='rtx' id='97' clockrate='90000'><parameter value='101' name='apt'/><rtcp-fb subtype='fir' type='ccm' xmlns='urn:xmpp:jingle:apps:rtp:rtcp-fb:0'/><rtcp-fb type='nack' xmlns='urn:xmpp:jingle:apps:rtp:rtcp-fb:0'/><rtcp-fb subtype='pli' type='nack' xmlns='urn:xmpp:jingle:apps:rtp:rtcp-fb:0'/></payload-type><payload-type name='rtx' id='99' clockrate='90000'><parameter value='107' name='apt'/></payload-type><rtp-hdrext xmlns='urn:xmpp:jingle:apps:rtp:rtp-hdrext:0' id='3' uri='http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time'/><rtp-hdrext xmlns='urn:xmpp:jingle:apps:rtp:rtp-hdrext:0' id='5' uri='http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01'/><rtcp-mux/><source name='jvb-v0' ssrc='2899368754' xmlns='urn:xmpp:jingle:apps:rtp:ssma:0'><ssrc-info owner='jvb' xmlns='http://jitsi.org/jitmeet'/><parameter value='mixedmslabel mixedlabelvideo0' name='msid'/></source></description><transport xmlns='urn:xmpp:jingle:transports:ice-udp:1' pwd='5kgqi2tg75qcbrpdt1qcu3mq7v' ufrag='4v0g71fjdhui5d'><web-socket url='wss://jitsi.example.com:443/colibri-ws/default-id/3d98b6b81f3edade/nre60ym5kkiokotr?pwd=5kgqi2tg75qcbrpdt1qcu3mq7v' xmlns='http://jitsi.org/protocol/colibri'/><rtcp-mux/><fingerprint required='false' setup='actpass' xmlns='urn:xmpp:jingle:apps:dtls:0' hash='sha-256'>F9:DB:16:C4:DB:19:E4:F0:20:6C:EF:AD:0A:38:DC:B9:24:07:1B:D7:15:04:3E:1D:95:3C:14:7A:66:67:B9:45</fingerprint><candidate foundation='1' id='11ef07f522aca03406e3ba77b' component='1' protocol='udp' generation='0' network='0' ip='xxx' port='10000' type='host' priority='2130706431'/><candidate foundation='2' id='486e533922aca0340ffffffffa1b231b0' component='1' protocol='udp' generation='0' network='0' ip='xxx' port='10000' type='host' priority='2130706431'/></transport></content><group xmlns='urn:xmpp:jingle:apps:grouping:0' semantics='BUNDLE'><content name='audio'/><content name='video'/></group><bridge-session id='12ae7' xmlns='http://jitsi.org/protocol/focus'/></jingle></iq>
Nov 01 11:50:33.055 DEBUG Received Jingle session-initiate from focus@auth.jitsi.example.com/focus
Nov 01 11:50:33.055 DEBUG adding ssrc to remote_ssrc_map: Source { id: "190519583", name: Some("jvb-a0"), parameters: [Parameter { name: "msid", value: Some("mixedmslabel mixedlabelaudio0") }], info: Some(SsrcInfo { owner: "jvb" }) }
Nov 01 11:50:33.055 DEBUG adding ssrc to remote_ssrc_map: Source { id: "2899368754", name: Some("jvb-v0"), parameters: [Parameter { name: "msid", value: Some("mixedmslabel mixedlabelvideo0") }], info: Some(SsrcInfo { owner: "jvb" }) }
Nov 01 11:50:33.055  WARN Remote DTLS fingerprint (verification not implemented yet): Fingerprint { hash: Sha_256, setup: Some(Actpass), required: Some("false"), value: [249, 219, 22, 196, 219, 25, 228, 240, 32, 108, 239, 173, 10, 56, 220, 185, 36, 7, 27, 215, 21, 4, 62, 29, 149, 60, 20, 122, 102, 103, 185, 69] }
Nov 01 11:50:33.055 DEBUG Local DTLS certificate:
-----BEGIN CERTIFICATE-----
MIIBUDCB96ADAgECAgh12bqLlt6qszAKBggqhkjOPQQDAjAhMR8wHQYDVQQDDBZy
Y2dlbiBzZWxmIHNpZ25lZCBjZXJ0MCAXDTc1MDEwMTAwMDAwMFoYDzQwOTYwMTAx
MDAwMDAwWjAhMR8wHQYDVQQDDBZyY2dlbiBzZWxmIHNpZ25lZCBjZXJ0MFkwEwYH
KoZIzj0CAQYIKoZIzj0DAQcDQgAET0NCKGCfDuMTIjJpRhq2yJV+5/qWTI4ffKlS
qrz5ttDV9hgrT0EbhD0iofD5EWU9BxYVwjhEI866t6DDVZ0VeqMXMBUwEwYDVR0R
BAwwCoIIZ3N0LW1lZXQwCgYIKoZIzj0EAwIDSAAwgQIhAMHKRDq1D9/efnfF5w65
kwmm6IJHaR3QTiAAxP4iwRtOAiB8vEBUMJd7wDfF2GF29J5mosdWXJtRC0DM/Hq2
zthAjg==
-----END CERTIFICATE-----

Nov 01 11:50:33.055 DEBUG Local DTLS fingerprint: 69:8A:70:7A:AF:31:37:23:FB:C:8:1B:4C:18:3:A4:7D:B6:98:8D:D8:0:75:A6:95:DC:53:C2:AC:56:57:CE
Nov 01 11:50:33.055 DEBUG audio SSRC: 1046210183
Nov 01 11:50:33.055 DEBUG video SSRC: 190517691
Nov 01 11:50:33.055 DEBUG video RTX SSRC: 2524423608
Nov 01 11:50:33.056 DEBUG XMPP    >>> <iq xmlns="jabber:client" from="nre60ym5kkiokotr@jitsi.example.com/Rd7ZwkQ6" id="bnJlNjB5bTVra2lva290ckBqaXRzaS0wMS50YS5kZS9SZDdad2tRNgA4RVFCRC03MjEA8dWe3ciFYT4irb3jIXm5CA==" to="test@conference.jitsi.example.com/focus" type="result"/>
Nov 01 11:50:33.056 DEBUG STUN address: Some(94.130.212.211:3478)
Nov 01 11:50:33.056 DEBUG TURN address: 94.130.212.211:5349
Nov 01 11:50:33.056 DEBUG ice_agent=Agent(ObjectRef { inner: 0x7f8b2803e000, type: NiceAgent })
Nov 01 11:50:33.056 DEBUG ice_stream_id=1
Nov 01 11:50:33.056 DEBUG ice_component_id=1
Nov 01 11:50:33.056 DEBUG setting ICE remote credentials
Nov 01 11:50:33.056 DEBUG gathering ICE candidates
Nov 01 11:50:33.057 DEBUG setting ICE remote candidates: [Candidate { component: 1, foundation: "1", generation: 0, id: "11ef07f522aca03406e3ba77b", ip: xxx, port: 10000, priority: 2130706431, protocol: "udp", rel_addr: None, rel_port: None, network: Some(0), type_: Host }, Candidate { component: 1, foundation: "2", generation: 0, id: "486e533922aca0340ffffffffa1b231b0", ip: xxx, port: 10000, priority: 2130706431, protocol: "udp", rel_addr: None, rel_port: None, network: Some(0), type_: Host }]
Nov 01 11:50:33.057 DEBUG candidate: Candidate { type_: Host, foundation: Ok("1"), addr: [2a01:4f8:10b:47a4::2]:10000, priority: 2130706431, stream_id: 1, component_id: 1, username: Ok("4v0g71fjdhui5d"), password: Ok("5kgqi2tg75qcbrpdt1qcu3mq7v") }
Nov 01 11:50:33.057 DEBUG candidate: Candidate { type_: Host, foundation: Ok("2"), addr: 94.130.212.211:10000, priority: 2130706431, stream_id: 1, component_id: 1, username: Ok("4v0g71fjdhui5d"), password: Ok("5kgqi2tg75qcbrpdt1qcu3mq7v") }
Nov 01 11:50:33.057 DEBUG building gstreamer pipeline
Nov 01 11:50:33.090 DEBUG linking video payloader -> rtpfunnel
Nov 01 11:50:33.090 DEBUG linking audio payloader -> rtpfunnel
Nov 01 11:50:33.090 DEBUG linking rtpfunnel -> rtpbin
Nov 01 11:50:33.091 DEBUG creating RTX sender for session 0
Nov 01 11:50:33.091 DEBUG rtpbin pad-added [(GstRtpBin) (GstRtpBin) rtpbin, (GstPad) (GstGhostPad) send_rtp_src_0]
Nov 01 11:50:33.091 DEBUG rtpbin pad-added [(GstRtpBin) (GstRtpBin) rtpbin, (GstPad) (GstGhostPad) send_rtp_sink_0]
Nov 01 11:50:33.091 DEBUG link dtlssrtpdec -> rtpbin
Nov 01 11:50:33.091 DEBUG rtpbin pad-added [(GstRtpBin) (GstRtpBin) rtpbin, (GstPad) (GstGhostPad) recv_rtp_sink_0]
Nov 01 11:50:33.091 DEBUG creating RTX receiver for session 0
Nov 01 11:50:33.091 DEBUG rtpbin pad-added [(GstRtpBin) (GstRtpBin) rtpbin, (GstPad) (GstGhostPad) recv_rtcp_sink_0]
Nov 01 11:50:33.091 DEBUG linking rtpbin -> dtlssrtpenc
Nov 01 11:50:33.091 DEBUG rtpbin pad-added [(GstRtpBin) (GstRtpBin) rtpbin, (GstPad) (GstGhostPad) send_rtcp_src_0]
Nov 01 11:50:33.091 DEBUG linking ice src -> dtlssrtpdec
Nov 01 11:50:33.091 DEBUG linking dtlssrtpenc -> ice sink
Nov 01 11:50:33.091 DEBUG local candidates: [Candidate { type_: Host, foundation: Ok("1"), addr: [fe80::b62e:99ff:fe45:389b%2]:34921, priority: 2013266431, stream_id: 1, component_id: 1, username: Ok(""), password: Ok("") }, Candidate { type_: Host, foundation: Ok("2"), addr: [xxx]:54909, priority: 2013266430, stream_id: 1, component_id: 1, username: Ok(""), password: Ok("") }, Candidate { type_: Host, foundation: Ok("3"), addr: 94.130.212.211:40265, priority: 2013266429, stream_id: 1, component_id: 1, username: Ok(""), password: Ok("") }]
Nov 01 11:50:33.091 DEBUG building Jingle session-accept
Nov 01 11:50:33.091 DEBUG XMPP    >>> <iq xmlns="jabber:client" from="nre60ym5kkiokotr@jitsi.example.com/Rd7ZwkQ6" id="749b3e66-320f-4ab1-b758-8a961300753e" to="test@conference.jitsi.example.com/focus" type="set"><jingle xmlns="urn:xmpp:jingle:1" action="session-accept" initiator="focus@auth.jitsi.example.com/focus" responder="nre60ym5kkiokotr@jitsi.example.com/Rd7ZwkQ6" sid="7cbj7p7dg114t"><content creator="responder" name="audio" senders="both"><description xmlns="urn:xmpp:jingle:apps:rtp:1" media="audio" ssrc="1046210183"><payload-type channels="2" clockrate="48000" id="111" name="opus"><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" type="transport-cc"/></payload-type><rtcp-mux/><source xmlns="urn:xmpp:jingle:apps:rtp:ssma:0" ssrc="1046210183"><parameter name="cname" value="54eefbab-ac0f-4789-9a6f-5c951ec70c39"/><parameter name="msid" value="8126139a-fb0c-456d-918b-832a61b8de02 5d1387bd-3658-4dc9-bfd9-defd7f076d42"/></source><rtp-hdrext xmlns="urn:xmpp:jingle:apps:rtp:rtp-hdrext:0" id="1" uri="urn:ietf:params:rtp-hdrext:ssrc-audio-level"/><rtp-hdrext xmlns="urn:xmpp:jingle:apps:rtp:rtp-hdrext:0" id="5" uri="http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01"/></description><transport xmlns="urn:xmpp:jingle:transports:ice-udp:1" pwd="mVNr5P6hU5mWi8rVaQH4+3" ufrag="Xe+5"><candidate component="1" foundation="1" generation="0" id="1ec7263f-a4d9-4ec4-90ba-e373646498e8" ip="xxx" port="34921" priority="2013266431" protocol="udp" type="host"/><candidate component="1" foundation="2" generation="0" id="e6f3484f-ecc7-4ae4-88c4-f77f9eb6b429" ip="xxx" port="54909" priority="2013266430" protocol="udp" type="host"/><candidate component="1" foundation="3" generation="0" id="773d4657-7907-4708-84dc-783c581fb82f" ip="xxx" port="40265" priority="2013266429" protocol="udp" type="host"/><fingerprint xmlns="urn:xmpp:jingle:apps:dtls:0" hash="sha-256" required="true" setup="active">69:8A:70:7A:AF:31:37:23:FB:0C:08:1B:4C:18:03:A4:7D:B6:98:8D:D8:00:75:A6:95:DC:53:C2:AC:56:57:CE</fingerprint></transport></content><content creator="responder" name="video" senders="both"><description xmlns="urn:xmpp:jingle:apps:rtp:1" media="video" ssrc="190517691"><payload-type clockrate="90000" id="100" name="VP8"><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" subtype="fir" type="ccm"/><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" type="nack"/><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" subtype="pli" type="nack"/><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" type="transport-cc"/></payload-type><payload-type clockrate="90000" id="96" name="rtx"><parameter name="apt" value="100"/></payload-type><rtcp-mux/><ssrc-group xmlns="urn:xmpp:jingle:apps:rtp:ssma:0" semantics="FID"><source ssrc="190517691"/><source ssrc="2524423608"/></ssrc-group><source xmlns="urn:xmpp:jingle:apps:rtp:ssma:0" ssrc="190517691"><parameter name="cname" value="8c3a3b5c-6f6a-49c5-8637-5d07d7286206"/><parameter name="msid" value="fff18f40-60b3-4bb3-b873-d35f3894d6c9 b95943bf-3665-4af0-a324-a7a5c643f93f"/></source><source xmlns="urn:xmpp:jingle:apps:rtp:ssma:0" ssrc="2524423608"><parameter name="cname" value="8c3a3b5c-6f6a-49c5-8637-5d07d7286206"/><parameter name="msid" value="fff18f40-60b3-4bb3-b873-d35f3894d6c9 b95943bf-3665-4af0-a324-a7a5c643f93f"/></source><rtp-hdrext xmlns="urn:xmpp:jingle:apps:rtp:rtp-hdrext:0" id="5" uri="http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01"/></description><transport xmlns="urn:xmpp:jingle:transports:ice-udp:1" pwd="mVNr5P6hU5mWi8rVaQH4+3" ufrag="Xe+5"><candidate component="1" foundation="1" generation="0" id="f6a049af-2dfe-4b64-bbc0-628f00332fed" ip="xxx" port="34921" priority="2013266431" protocol="udp" type="host"/><candidate component="1" foundation="2" generation="0" id="11cc5179-4598-4752-bdde-371f29d44fe6" ip="xxx" port="54909" priority="2013266430" protocol="udp" type="host"/><candidate component="1" foundation="3" generation="0" id="63d55003-187a-4e58-8462-c201d044c027" ip="xxx" port="40265" priority="2013266429" protocol="udp" type="host"/><fingerprint xmlns="urn:xmpp:jingle:apps:dtls:0" hash="sha-256" required="true" setup="active">69:8A:70:7A:AF:31:37:23:FB:0C:08:1B:4C:18:03:A4:7D:B6:98:8D:D8:00:75:A6:95:DC:53:C2:AC:56:57:CE</fingerprint></transport></content></jingle></iq>
Nov 01 11:50:33.107 DEBUG XMPP    <<< <iq from='test@conference.jitsi.example.com/focus' id='749b3e66-320f-4ab1-b758-8a961300753e' xmlns='jabber:client' type='result' to='nre60ym5kkiokotr@jitsi.example.com/Rd7ZwkQ6'/>
Nov 01 11:50:33.107 DEBUG Focus acknowledged session-accept
Nov 01 11:50:33.107  INFO Connecting Colibri WebSocket to wss://jitsi.example.com:443/colibri-ws/default-id/3d98b6b81f3edade/nre60ym5kkiokotr?pwd=5kgqi2tg75qcbrpdt1qcu3mq7v
Nov 01 11:50:33.114 DEBUG Client handshake done.
Nov 01 11:50:33.114  INFO Connected Colibri WebSocket
Nov 01 11:50:33.114 DEBUG Colibri <<< {"colibriClass":"ServerHello"}
Nov 01 11:50:33.114 DEBUG Colibri <<< {"colibriClass":"SenderVideoConstraints", "videoConstraints":{"idealHeight":180}}
Nov 01 11:50:33.114 DEBUG join{xmpp_connection=Connection { tx: Sender { chan: Tx { inner: Chan { tx: Tx { block_tail: 0x5617f2e1d010, tail_position: 6 }, semaphore: (Semaphore { permits: 64 }, 64), rx_waker: AtomicWaker, tx_count: 3, rx_fields: "..." } } }, inner: Mutex { data: ConnectionInner { state: Idle, jid: Some(FullJID(nre60ym5kkiokotr@jitsi.example.com/Rd7ZwkQ6)) } } } glib_main_context=MainContext(Shared { inner: 0x5617f2e1cac0 }) config=JitsiConferenceConfig { muc: BareJID(test@conference.jitsi.example.com), focus: Full(FullJID(focus@auth.jitsi.example.com/focus)), nick: "bot-user", region: None, video_codec: "vp8", extra_muc_features: [] }}: close time.busy=22.0µs time.idle=121ms
Nov 01 11:50:33.114 DEBUG add_bin{self=JitsiConference { jid: FullJID(nre60ym5kkiokotr@jitsi.example.com/Rd7ZwkQ6), config: JitsiConferenceConfig { muc: BareJID(test@conference.jitsi.example.com), focus: Full(FullJID(focus@auth.jitsi.example.com/focus)), nick: "bot-user", region: None, video_codec: "vp8", extra_muc_features: [] }, inner: Mutex { data: JitsiConferenceInner { state: Idle } } } bin=Bin(ObjectRef { inner: 0x5617f2c39030, type: GstBin })}: close time.busy=50.3µs time.idle=729ns
Nov 01 11:50:33.114  INFO Found audio element in pipeline, linking...
Nov 01 11:50:33.114 DEBUG set_muted{self=JitsiConference { jid: FullJID(nre60ym5kkiokotr@jitsi.example.com/Rd7ZwkQ6), config: JitsiConferenceConfig { muc: BareJID(test@conference.jitsi.example.com), focus: Full(FullJID(focus@auth.jitsi.example.com/focus)), nick: "bot-user", region: None, video_codec: "vp8", extra_muc_features: [] }, inner: Mutex { data: JitsiConferenceInner { state: Idle } } } media_type=Video muted=true}:send_presence{self=JitsiConference { jid: FullJID(nre60ym5kkiokotr@jitsi.example.com/Rd7ZwkQ6), config: JitsiConferenceConfig { muc: BareJID(test@conference.jitsi.example.com), focus: Full(FullJID(focus@auth.jitsi.example.com/focus)), nick: "bot-user", region: None, video_codec: "vp8", extra_muc_features: [] }, inner: Mutex { data: JitsiConferenceInner { state: Idle } } } payloads=[Element { name: "videomuted", namespace: "jabber:client", prefix: None, prefixes: Prefixes(), attributes: {}, children: [Text("true")] }]}: close time.busy=6.92µs time.idle=502ns
Nov 01 11:50:33.114 DEBUG set_muted{self=JitsiConference { jid: FullJID(nre60ym5kkiokotr@jitsi.example.com/Rd7ZwkQ6), config: JitsiConferenceConfig { muc: BareJID(test@conference.jitsi.example.com), focus: Full(FullJID(focus@auth.jitsi.example.com/focus)), nick: "bot-user", region: None, video_codec: "vp8", extra_muc_features: [] }, inner: Mutex { data: JitsiConferenceInner { state: Idle } } } media_type=Video muted=true}: close time.busy=24.2µs time.idle=595ns
Nov 01 11:50:33.114 DEBUG XMPP    >>> <presence xmlns="jabber:client" to="test@conference.jitsi.example.com/nre60ym5kkiokotr"><videomuted>true</videomuted></presence>
Nov 01 11:50:33.114 DEBUG set_pipeline_state{self=JitsiConference { jid: FullJID(nre60ym5kkiokotr@jitsi.example.com/Rd7ZwkQ6), config: JitsiConferenceConfig { muc: BareJID(test@conference.jitsi.example.com), focus: Full(FullJID(focus@auth.jitsi.example.com/focus)), nick: "bot-user", region: None, video_codec: "vp8", extra_muc_features: [] }, inner: Mutex { data: JitsiConferenceInner { state: Idle } } } state=Playing}: close time.busy=111µs time.idle=475ns
Nov 01 11:50:33.115 DEBUG XMPP    <<< <presence from='test@conference.jitsi.example.com/nre60ym5kkiokotr' xmlns='jabber:client' to='nre60ym5kkiokotr@jitsi.example.com/Rd7ZwkQ6'><videomuted>true</videomuted><x xmlns='vcard-temp:x:update'/><x xmlns='http://jabber.org/protocol/muc#user'><item jid='nre60ym5kkiokotr@jitsi.example.com/Rd7ZwkQ6' affiliation='none' role='participant'/><status code='110'/></x></presence>
Nov 01 11:50:33.119 DEBUG audio payloader requested extension: 1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
Nov 01 11:50:33.120 DEBUG audio payloader requested extension: 5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
Nov 01 11:50:33.120 ERROR ../plugins/elements/gstqueue.c(1570): gst_queue_loop (): /GstPipeline:pipeline0/GstBin:bin0/GstQueue:queue0:
streaming stopped, reason not-negotiated (-4)
Nov 01 11:50:34.174 DEBUG Colibri <<< {"colibriClass":"SenderVideoConstraints", "videoConstraints":{"idealHeight":2160}}
Nov 01 11:50:34.174  INFO Colibri message: SenderVideoConstraints { video_constraints: Constraints { ideal_height: Some(2160), max_height: None } }
Nov 01 11:50:34.914 DEBUG Colibri <<< {"colibriClass":"EndpointMessage","to":"nre60ym5kkiokotr","from":"4d56b101","msgPayload":{"type":"e2e-ping-request","id":2}}
Nov 01 11:50:34.914  INFO Colibri message: EndpointMessage { from: Some("4d56b101"), to: Some("nre60ym5kkiokotr"), msg_payload: Object({"id": Number(2), "type": String("e2e-ping-request")}) }
Nov 01 11:50:43.124 DEBUG Colibri <<< {"colibriClass":"EndpointMessage","to":"nre60ym5kkiokotr","from":"4d56b101","msgPayload":{"type":"e2e-ping-request","id":3}}
Nov 01 11:50:43.124  INFO Colibri message: EndpointMessage { from: Some("4d56b101"), to: Some("nre60ym5kkiokotr"), msg_payload: Object({"id": Number(3), "type": String("e2e-ping-request")}) }
Nov 01 11:50:43.972 DEBUG Colibri <<< {"colibriClass":"EndpointStats","from":"4d56b101","bitrate":{"upload":0,"download":0,"audio":{"upload":0,"download":0},"video":{"upload":0,"download":0}},"packetLoss":{"total":0,"download":0,"upload":0},"connectionQuality":100,"jvbRTT":61}
Nov 01 11:50:43.972  INFO Colibri message: EndpointStats { from: Some("4d56b101"), bitrate: Bitrates { audio: Bitrate { upload: 0, download: 0 }, video: Bitrate { upload: 0, download: 0 }, total: Bitrate { upload: 0, download: 0 } }, packet_loss: PacketLoss { total: 0, download: 0, upload: 0 }, connection_quality: 100.0, jvb_rtt: Some(61), server_region: None, max_enabled_resolution: None }
Nov 01 11:50:48.874 DEBUG ICE candidate-gathering-done 1
Nov 01 11:50:53.081 DEBUG Colibri <<< {"colibriClass":"EndpointMessage","to":"nre60ym5kkiokotr","from":"4d56b101","msgPayload":{"type":"e2e-ping-request","id":4}}
Nov 01 11:50:53.081  INFO Colibri message: EndpointMessage { from: Some("4d56b101"), to: Some("nre60ym5kkiokotr"), msg_payload: Object({"id": Number(4), "type": String("e2e-ping-request")}) }
Nov 01 11:50:53.971 DEBUG Colibri <<< {"colibriClass":"EndpointStats","from":"4d56b101","bitrate":{"upload":0,"download":0,"audio":{"upload":0,"download":0},"video":{"upload":0,"download":0}},"packetLoss":{"total":0,"download":0,"upload":0},"connectionQuality":100,"jvbRTT":16}
Nov 01 11:50:53.971  INFO Colibri message: EndpointStats { from: Some("4d56b101"), bitrate: Bitrates { audio: Bitrate { upload: 0, download: 0 }, video: Bitrate { upload: 0, download: 0 }, total: Bitrate { upload: 0, download: 0 } }, packet_loss: PacketLoss { total: 0, download: 0, upload: 0 }, connection_quality: 100.0, jvb_rtt: Some(16), server_region: None, max_enabled_resolution: None }
Nov 01 11:51:03.145 DEBUG Colibri <<< {"colibriClass":"EndpointMessage","to":"nre60ym5kkiokotr","from":"4d56b101","msgPayload":{"type":"e2e-ping-request","id":5}}
Nov 01 11:51:03.145  INFO Colibri message: EndpointMessage { from: Some("4d56b101"), to: Some("nre60ym5kkiokotr"), msg_payload: Object({"id": Number(5), "type": String("e2e-ping-request")}) }
Nov 01 11:51:04.091 DEBUG Colibri <<< {"colibriClass":"EndpointStats","from":"4d56b101","bitrate":{"upload":0,"download":0,"audio":{"upload":0,"download":0},"video":{"upload":0,"download":0}},"packetLoss":{"total":0,"download":0,"upload":0},"connectionQuality":100,"jvbRTT":86}
Nov 01 11:51:04.091  INFO Colibri message: EndpointStats { from: Some("4d56b101"), bitrate: Bitrates { audio: Bitrate { upload: 0, download: 0 }, video: Bitrate { upload: 0, download: 0 }, total: Bitrate { upload: 0, download: 0 } }, packet_loss: PacketLoss { total: 0, download: 0, upload: 0 }, connection_quality: 100.0, jvb_rtt: Some(86), server_region: None, max_enabled_resolution: None }```

Do you have any idea which lib could be missing?

**Comment by mkn-ta** [comment]
So now we´ve able to play some YouTube link, the YouTube video is running in Jitsi but we´re don´t get audio and it seems that this is the same problem with an mp3 file.
The problem seems to be:

Nov 04 11:49:58.189 ERROR ../libs/gst/base/gstbasesrc.c(3127): gst_base_src_loop (): /GstPipeline:pipeline0/GstBin:bin0/GstCurlHttpSrc:curlhttpsrc0:
streaming stopped, reason not-negotiated (-4)
Nov 04 11:49:58.190 ERROR ../plugins/elements/gstqueue.c(992): gst_queue_handle_sink_event (): /GstPipeline:pipeline0/GstBin:bin0/GstQueue:queue0:
streaming stopped, reason not-negotiated (-4)

But we don´t have an idea what´s missing.

**Comment by jbg** [comment]
There are instructions for debugging your GStreamer pipeline in the README, which I also mentioned in a comment above. The short verison is: set the environment variable `GST_DEBUG` to a number (3 or 4 is usually enough) and GStreamer will print a lot of debugging information, which will generally point to the issue.

Feel free to paste that log output here, but please put ``` above and below of the log so that it gets formatted verbatim, otherwise GitHub will interpret parts of the log as formatting characters and mangle it.

`streaming stopped, reason not-negotiated` suggests that two elements are linked which are not compatible with each other, probably indicating a missing element.

**Comment by jbg** [comment]
I tested with your pipeline and found that a `capsfilter` element being added by gst-meet now causes this `not-negotiated` error, either due to some GStreamer changes or due to some other changes in our hdrext handling.

It should be fixed in latest master.

**Comment by mkn-ta** [comment]
That helped, now we can play YouTube videos and .mp3 files to Jitsi - thanks! :-)

**Comment by serenaraju** [comment]
> ```
> Oct 19 07:52:45.457 DEBUG Received non-Jingle IQ
> ```
> 
> I think this might have been Jitsi's non-standard jingle element failing to parse correctly. Please try again with latest master, and if it still doesn't work, please send your logs formatted as code as @linkmauve suggested above.

I built the repo from the source and run the command as specified but I am still getting a non-JIngle error like this. Also, I have installed all the plugins required (base, good, bad, ugly). Still there is no change in the error. Would you know why that is?

**Comment by jbg** [comment]
This message alone is not an error; it's logged at DEBUG level and just tells us an IQ was sent that we didn't handle. In many cases this isn't a problem as the IQ was safe to ignore. If you're having a problem, I'd need more context (both details of what problem you're having, and the full log) to assist.

**Comment by serenaraju** [comment]
> 

Oh, thank you. I have added the full log in a new issue. What might be causing the issues?
